### ISSUE TITLE
Issue/TODO triage

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#359]
Let's gather and discuss several smaller problems and TODOs, that could be then transformed into their own issues.

**Improvements**
- [x] Rule configuration should not be a single string - the options that rules require should be explicitly defined, multi-valued and possibly type-checked.
- [x] Metadata should be generic key-value, so parts of the application such as rules are able to store custom metadata. There should be a clean separation between meta values that users can just see, can see and edit, and private ones.
- [ ] Artifact must exist (and there must be some content) to create artifact rules. Therefore users cannot define artifact rules (specifically application type CREATE) before actually adding the content for the first time (global rules work). The same applies in case of metadata. I suggest we separate creation of an artifact into just defining an empty version sequence (so the creation will not require initial content), and the first content will be added by an update operation. This may allow us to remove distinction between rule application type CREATE and UPDATE.
- [ ] Alternatively, we could remove distinction between creation and updating of an artifact, because we are adding content in both cases.
- [x] `getArtifactIds` operation will become costly unless cached or paged
- [x] Consider making artifact immutable/append-only, i.e. you can not delete artifact versions, only whole artifact. A replacement would be the artifact state feature implemented using metadata (i.e. a `DELETED` state). This would support the `git` metaphor and auditing.

**Code Quality**
- [x] Use [code quality tools](https://github.com/gregswindle/maven-code-quality-pom/blob/master/README.md) and maven plugins, such as FindBugs or PMD
- [x] Use List instead of a SortedSet where ordering matters, there is a difference between ordered and sorted collection, unless it's explicitly stated that it's the same for the given use-case
- [x] More use of `Optional` and explicit null checks
- [x] Use of Lombok where possible
- [ ]  Improve `StoredArtifact` - rename it to `ArtifactVersion` / `StoredArtifactVersion`, rename field `id` to `globalId`, and it should contain `artifactId` field
- [ ] Methods that return `CompletionStage` should not throw exceptions
- [x] We use `long` IDs, but some other systems use `int`. Make sure the conversion is safe and fails gracefully - there are unsafe calls to `.intValue()`
- [x] There is a possible race condition in generating IDs in JPA storage

**Docs**
- [x] Explicitly define basic concepts in a `README` and/or javadoc, e.g. what is an artifact, artifact version etc. Make sure this is reflected in naming of variables and methods.
- [x] In addition, add definitions (in javadoc) to all conceptual model classes (and enums) e.g. validity level and artifact state

**TODOs/Tasks**
- [x] Reflect `ArtifactState` in Compat API, i.e. if an artifact is in a `DELETED` state, do not return it in REST calls
- [x] Make sure Compat API supports multiple artifact types, in addition to Avro, if it's done in the spec.

We can use this format to discuss issues that we come across in the code and replace TODO comments. Feel free to add more here.

**Comment by EricWittmann** [comment]
@jsenko Can you review this and see which things are still relevant and you'd like to keep open?

**Comment by jsenko** [comment]
I've checked issues that I think are no longer relevant or there are already tracked AFAIK. Do you think the unchecked items are valid & need their tracking issues? I can create them and we can close this.

**Comment by jsenko** [comment]
@carlesarnal hi, can you take a look at the last two items related to the CCompat API and see if they are valid?

**Comment by carlesarnal** [comment]
Checked, both done.

**Comment by EricWittmann** [comment]
Maybe create an issue for "Methods that return CompletionStage should not throw exceptions" but otherwise I say we close this.
